// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxgygqznwmjilnctnoqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4Z3lncXpud21qaWxuY3Rub3FtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NTY5MTMsImV4cCI6MjA2ODQzMjkxM30.ePJi60SWbpVrGXMN0X5lNtpUE9DSHThUv4xqI1ptZrE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});